### ISSUE TITLE
Should brio error on invalid UTF-8 sequences?

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/brio#5]
``` r
x <- as.raw(c(0xc3, 0x28))
writeBin(x, tmp <- tempfile())
y <- brio::read_file(tmp)
charToRaw(y)
#> [1] c3 28
Encoding(y)
#> [1] "UTF-8"
stringi::stri_enc_isutf8(y)
#> [1] FALSE
```

<sup>Created on 2020-07-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
I don't really think UTF-8 validation is in scope. Even if we were to do this, how are you suggesting we do the validation?

**Comment by gaborcsardi** [comment]
Yeah, I thought that it might not be in scope, that's fine.
